config/routes.rb
Rails.application.routes.draw do
 
  get 'about_us/index'

  root 'home#index'
  # get 'quotes/index'
  resources :quotes
  devise_for :users , controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  	@quotes = Quote.all
  end

  def new
  	@quote = Quote.new
  end

   def show
    @quote = Quote.find(params[:id])
  end

  def edit
  	@quote = Quote.find(params[:id])
  end

  def destroy
  	Quote.find(params[:id]).destroy
  	redirect_to quotes_path
  end

  def create
  	if Quote.create(quote_params)
  		flash[:success] = "Thank you!!!"
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  private

  def quote_params
  	params.require(:quote).permit(:fname, :lname, :address, :service, :city, :description, :zip, :email, :complete, :state, :phone_num)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/about_us/index.html.erb
 
	<div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h2 class="header center teal-text text-lighten-2">Who Are We?</h2>
          <!--   Icon Section   -->
          <div class="row">
            <div class="col s12 m6">
              <div class="icon-block">
                <div class="">
                	<%= image_tag "family1.png", size: "600x500" %>
                </div>
              </div>
            </div>

            <div class="col s12 m6">
              <div class="icon-block">
                <p class="light">orem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque</p>

                <p class="light">orem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat.</p>
              </div>
            </div>
          </div>
          <p class="light">orem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque</p>
        </div>
      </div>

    </div>

    <div class="row center">
    <%= link_to root_path + "#Contact"  do %>
      <button id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Contact Us</button>
    <% end %>
  </div>

app/views/home/index.html.erb
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Triple B Enterprises</h1>
        <div class="row center">
          <h5 class="header col s12 dark black-text teal lighten-5"><b>Your Neigbouring Cleaning, Car Rental and General Services Crew!</b></h5>
        </div>
        <div class="row center">
          <%= link_to quotes_path do %>
            <button id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Quote</button>
          <% end %>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><%= image_tag "house.png", size: "600x600" %></div>
  </div>

 <div class="container">
    <div class="section" id="Services">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">home</i></h2>
            <h5 class="center">Cleaning Services</h5>

            <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">directions_car</i></h2>
            <h5 class="center">Car Rental</h5>

            <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">shopping_cart</i></h2>
            <h5 class="center">General Services</h5>

            <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque</p>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="parallax-container valign-wrapper">
    <div class="parallax"><%= image_tag "car_rental.png"%></div>
    <br><br>
  </div>
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Why Choose Us?</h4>
          <!--   Icon Section   -->
          <div class="row">
            <div class="col s12 m4">
              <div class="icon-block">
                <h2 class="center brown-text"><i class="material-icons">attach_money</i></h2>
                <h5 class="center">Our Prices</h5>

                <p class="light">We are very affordable and reasonably priced. </p>
              </div>
            </div>

            <div class="col s12 m4">
              <div class="icon-block">
                <h2 class="center brown-text"><i class="material-icons">location_on</i></h2>
                <h5 class="center">Location</h5>

                <p class="light">We are located close to you and would provide our services in a timely manner. </p>
              </div>
            </div>

            <div class="col s12 m4">
              <div class="icon-block">
                <h2 class="center brown-text"><i class="material-icons">shopping_cart</i></h2>
                <h5 class="center">Our Services</h5>

                <p class="light">We provide premium services to every customer that patronizes us.</p>
              </div>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container" id="Contact">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Location</h1>
        <div class="row center">
          <h5 class="header col s12 dark black-text">
            <b>T: +1672450981<br/>
               +17672958826<br/>
               +17676161070</b>
          </h5>
          <h5 class="header col s12 dark black-text">
            <b>E: admin@admin.mail.com</b>
          </h5>
          <h5 class="header col s12 dark black-text">
            <b>Address: <br/>
            Lot 2 Bath Estate <br/>
            Roseau, Dominica</b>
          </h5>
        </div>
        <br><br>
      </div>
    </div>
    <div class="parallax"><%= image_tag "m4.png" %></div>
  </div>
  <br>
  <div class="row center">
    <%= link_to quotes_path do %>
      <button id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Quote</button>
    <% end %>
  </div>
  

app/views/layouts/_footer.html.erb
<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae</p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><%= link_to "Home", root_path, class: "white-text" %></li>
          <li><%= link_to "Services", root_path + "#Services", class: "white-text" %></li>
          <li><%= link_to "Qoutes", quotes_path, class: "white-text" %></li>
          <li><%= link_to "Contact Us", root_path + "#Contact", class: "white-text" %></li>
          <li><a href=""><%= link_to 'Join Us', edit_user_registration_path, class: "white-text" %></a></li>
          <li><%= link_to "About Us", about_us_index_path, class: "white-text" %></li> 
          <li><a class="white-text"><b>Call Us: +1672450981</b></a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="">Facebook</a></li>
          <li><a class="white-text" href="">Twitter</a></li>
          <li><a class="white-text" href="">Instagram</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">Cleaning</a></li>
  <li><a href="#!">Car Rental</a></li>
  <li class="divider"></li>
  <li><a href="#!">General Services</a></li>
</ul>

<nav class="white" role="navigation" data-target="header">
  <div class="nav-wrapper container">
    <%= link_to root_path do %>
      <%= image_tag "TB_logo.png", size: "95x62", class: "brand-logo", id: "logo-container"%>
    <% end %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Services", root_path + "#Services" %></li>
      <li><%= link_to "Qoutes", quotes_path %></li>
      <li><%= link_to "Contact Us", root_path + "#Contact" %></li>
      <li><%= link_to "About Us", about_us_index_path %></li> 
      <% if user_signed_in? %>
        <li><%= link_to "Requests", about_us_index_path %></li> 
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><a href=""><%= link_to 'Join Us', edit_user_registration_path %></a></li>
      <% end %>
      <li><a class="teal-text"><b>Call Us: +1672450981</b></a></li>
      
    </ul>

    <ul id="nav-mobile" class="sidenav">
      <li><%= link_to "Services", root_path + "#Services" %></li>
      <li><%= link_to "Qoutes", quotes_path %></li>
      <li><%= link_to "Contact Us", root_path + "#Contact" %></li>
      <li><%= link_to "About Us", about_us_index_path %></li> 
      <% if user_signed_in? %>
        <li><%= link_to "Requests", about_us_index_path %></li> 
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><a href=""><%= link_to 'Join Us', edit_user_registration_path %></a></li>
      <% end %>
      <li><a class="teal-text"><b>Call Us: +1672450981</b></a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Triple B Enterprises</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">   

    <style>
      nav ul a,
      nav .brand-logo {
        color: #444;
      }

      p {
        line-height: 2rem;
      }

      .sidenav-trigger {
        color: #26a69a;
      }

      .parallax-container {
        min-height: 380px;
        line-height: 0;
        height: auto;
        color: rgba(255,255,255,.9);
      }
        .parallax-container .section {
          width: 100%;
        }

      @media only screen and (max-width : 992px) {
        .parallax-container .section {
          position: absolute;
          top: 40%;
        }
        #index-banner .section {
          top: 10%;
        }
      }

      @media only screen and (max-width : 600px) {
        #index-banner .section {
          top: 0;
        }
      }

      .icon-block {
        padding: 0 15px;
      }
      .icon-block .material-icons {
        font-size: inherit;
      }

      footer.page-footer {
        margin: 0;
      }
    </style>
  </head>

  <body>
    <div>
      <div id="navbar">
        <%= render(partial: 'layouts/navbar') %>
      </div> 
      <%= yield %>           
      <%= render(partial: 'layouts/footer') %>
      <!--  Scripts-->
      <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <%= javascript_include_tag 'materialize', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'init', 'data-turbolinks-track': 'reload' %>
    </div>  	
  </body>
</html>

app/views/quotes/index.html.erb
<div class="container">

	<div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>How It Works</h4>
          <!--   Icon Section   -->
          <div class="row">
            <div class="col s12 m6">
              <div class="icon-block">
                <h2 class="center brown-text"><i class="material-icons">border_color</i></h2>
                <h5 class="center">Fill Form</h5>

                <p class="light">Fill out the form with your information and a detailed description of service needed.</p>
              </div>
            </div>

            <div class="col s12 m6">
              <div class="icon-block">
                <h2 class="center brown-text"><i class="material-icons">attach_money</i></h2>
                <h5 class="center">Estimates</h5>

                <p class="light">An estimate would be sent to you via email. For more information contact us.</p>
              </div>
            </div>
          </div>

        </div>
      </div>

    </div>
    
    <div class="card teal lighten-5">
			<%= form_for Quote.new, html: { class: "container"} do |f| %>
				<h5 class="center">Please fill...</h5><br/>
				First name: <%=f.text_field :fname, placeholder: "Jane", :required => 'required'%>
				Last name: <%=f.text_field :lname, placeholder: "Doe", :required => 'required'%>
				Email Address: <%=f.text_field :email, placeholder: "JaneDoe@email.com", :required => 'required'%>
				Address: <%=f.text_field :address, placeholder: "543 North West", :required => 'required'%>
				City: <%=f.text_field :city, placeholder: "Roseu"%>
				State: <%=f.text_field :state, placeholder: "Roseu"%>
				Zip Code: <%=f.text_field :zip, placeholder: "54387"%>
				Phone Number: <%=f.text_field :phone_num, placeholder: "543-454-4545"%>
				Service?  Rental/Cleaning/Gen. Service  : <%= f.text_field :service, placeholder: "cleaning" %>
				Description: <%=f.text_field :description, placeholder: "House cleaning, 4 bed, 2 baths and laundry"%>

				<%= f.hidden_field :complete, :value => false %>
				<p class="center waves-effect waves-light btn"><%= f.submit %><br/></p>
			<%end%>
    </div>
	
	<br><br>

</div>